name: flutter_adict_news
description: "A test task for the Adict company."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  get_it: ^7.7.0
  auto_route: ^8.1.3
  flutter_dotenv: ^5.1.0
  dio: ^5.4.3+1

  news_repository:
    path: ./packages/news_repository
  infinite_scroll_pagination: ^4.0.0
  figma_squircle: ^0.5.3
  sliver_tools: ^0.2.12
  connectivity_plus: ^6.0.3
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  auto_route_generator: ^8.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env